# version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: local-nginx
    hostname: nginx
    ports:
      - 8808:80
      - 8803:443
    volumes:
      - ../src/server:/usr/share/nginx
      - ./nginx/log:/var/log/nginx/
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Europe/Moscow"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    container_name: local-php
    hostname: php
    volumes:
      - ../src/server:/usr/share/nginx
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./app-log:/var/log/app/
      - ./php/log:/var/log/php-fpm/
      # - ./php/tmp:/tmp/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: "Europe/Moscow"
  db:
    image: mysql:8.4.2
    container_name: local-db
    hostname: db
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/data/mysql-db/8.4.2:/var/lib/mysql
