version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: local-nginx
    hostname: nginx
    ports:
      - 8888:80
      - 8883:443
    volumes:
      - ../src/server:/usr/share/nginx
      - ./nginx/log:/var/log/nginx/
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Europe/Moscow"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    container_name: local-php
    hostname: php
    volumes:
      - ../src/server:/usr/share/nginx
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./app-log:/var/log/app/
      - ./php/log:/var/log/php-fpm/
      # - ./php/tmp:/tmp/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: "Europe/Moscow"

